name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install deb dependencies
        run: |
          sudo apt update
          sudo apt install pandoc
      - name: Install dependencies
        run: |
          pip install pycodestyle coverage pytest pypandoc
          python3 setup.py install
      - name: Run pycodestyle
        run: |
          pycodestyle --exclude=venv --ignore=E501 .
      - name: Run pytest
        run: |
          coverage run --source=. -m pytest
      - name: Generate coverage report
        run: |
          coverage report -m
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
